name: Static Site Deploy (pnpm)

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "24"
      pnpm-version:
        required: false
        type: string
        default: "11.9.0"
      dist-path:
        required: false
        type: string
        default: "./dist"

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          version: ${{ inputs.pnpm-version }}

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.dist-path }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
